-- Catetin migration 003: receipt/bill photo attachments
-- Run this once in your EXISTING Supabase project's SQL Editor.
-- Safe to re-run.

alter table transactions add column if not exists receipt_url text;

-- Private bucket - photos are only readable via a short-lived signed URL
-- generated by the app for the owning user, never a public link.
insert into storage.buckets (id, name, public)
values ('receipts', 'receipts', false)
on conflict (id) do nothing;

alter table storage.objects enable row level security;

-- Files are stored as "{user_id}/{transaction_id}.jpg", so the first path
-- segment doubling as the owner check is enough to keep everyone's receipts
-- private to themselves.
drop policy if exists "own receipt insert" on storage.objects;
create policy "own receipt insert" on storage.objects
  for insert with check (bucket_id = 'receipts' and (storage.foldername(name))[1] = auth.uid()::text);

drop policy if exists "own receipt select" on storage.objects;
create policy "own receipt select" on storage.objects
  for select using (bucket_id = 'receipts' and (storage.foldername(name))[1] = auth.uid()::text);

drop policy if exists "own receipt update" on storage.objects;
create policy "own receipt update" on storage.objects
  for update using (bucket_id = 'receipts' and (storage.foldername(name))[1] = auth.uid()::text);

drop policy if exists "own receipt delete" on storage.objects;
create policy "own receipt delete" on storage.objects
  for delete using (bucket_id = 'receipts' and (storage.foldername(name))[1] = auth.uid()::text);
